### PR TITLE
Use direct cradle for tests when stack is not available

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by expipiplus1** [comment]
This does tend to scatter interface and object files around in `test/testdata`, but `-outputdir` in the direct options doesn't seem to do anything to help.

**Comment by fendor** [comment]
And the tests all succeed?

**Comment by expipiplus1** [comment]
A lot more than before!

A few still fail for me for what look to be reasons unrelated to this
change. Not 100% sure though. I'll post a log when I'm home in a few days

**Comment by fendor** [comment]
Azure CI: https://dev.azure.com/powerwalross/powerwalross/_build/results?buildId=212
Circle CI: https://circleci.com/workflow-run/a0f4108f-391c-46c3-9f28-d70eedcd920f
Manually triggered.

EDIT: Dammit, I hoped this would resolve the failing tests :(

**Comment by expipiplus1** [comment]
Thanks, sorry for forgetting about that log!

**Pull request merged**
